### ISSUE TITLE
extending FAIR recommendations and documentation

### ISSUE THREAD

**Issue by AkshayDevkate** [Software-Engineering-Group-UP/SWORDS-template-UP#19]
**Description:**  
Enhance and restructure the `collect_variables` scripts to perform the following:  

1. **License Analysis:**  
   - Update `collect_variables/scripts/howfairis_api` to analyze the most used licenses:  
     - Copyleft  
     - Permissive  
     - Proprietary  

2. **Readme Analysis:**  
   - Extend `collect_variables/scripts/parse_readme` to:  
     - Check for the presence of code review checklists and software quality checklists mentioned in the README (beyond those recommended by `howfairis_api` like OpenSSF badge).  
     - Verify if contributing guidelines are present in the repository.  

3. **Data License and Folder Analysis:**  
   - Check if there is a folder named `data` in the root directory.  
   - Verify if a data license is mentioned in the README.  

4. **Documentation Update:**  
   - Update the documentation to reflect the changes and provide stepwise instructions for using the scripts.  

5. **Script Restructuring:**  
   - Rearrange the scripts for modularity and ease of stepwise execution.  

**Tasks:**  
- [ ] Analyze license types (copyleft, permissive, proprietary) using `howfairis_api`.  
- [ ] Extend `parse_readme` to detect additional checklists and contributing guidelines.  
- [ ] Check for the `data` folder and data license mention in the README.  
- [ ] Update documentation to describe the new functionality.  
- [ ] Restructure scripts for better modularity and stepwise usability.

**Comment by AkshayDevkate** [comment]
**Testing** 

- **Presence of Test/Tests folder.** 

The folder should be present in the root directory of the repository. folder names - test, tests, gtest, catch2. 

- **Test file naming conventions.**

| Language | Common Test Folder Names      | Common File Naming Conventions                           | Frameworks                                                                 |
|----------|-------------------------------|---------------------------------------------------------|----------------------------------------------------------------------|
| Python   | `tests`, `test`               | `test_*.py`, `*_test.py`                                | `unittest` and `pytest`. |
| R        | `tests`, `tests/testthat`, `tests/tinytest` | `test-*.R` (for `testthat`), `*.R` (for `tinytest`)     | `testthat` framework requires `testthat.R`. `tinytest` allows tests in `tests/tinytest`. |
| C++      | `tests`, `test`, `gtest`, `catch2` | `*_test.cpp`, `test_*.cpp`                              |  Google Test or Catch2.   |


- **Test types.** 

| Language | Root Test Folder              | Look subfolders for testing types                         | 
|----------|-------------------------------|------------------------------------------------------------|
| Python   | `tests`, `test`               |  `unit`, `integration`, `system`, `e2e`, `performance`, `regression`, `functional`, `acceptance`, `security`, `sanity` , `mutation`, `metamorphic`|
| R        | `tests`, `tests/testthat`, `tests/tinytest` |  `unit`, `integration`, `system`, `e2e`, `performance`, `regression`, `functional`, `acceptance`, `security`, `sanity` , `mutation`, `metamorphic` | 
| C++      | `tests`, `test`, `gtest`, `catch2` | `unit`, `integration`, `system`, `e2e`, `performance`, `regression`, `functional`, `acceptance`, `security`, `sanity` , `mutation`, `metamorphic`|

**Comment by AkshayDevkate** [comment]
README Extentions -

CONTRIBUTING - 
CONTRIBUTING.rst
CONTRIBUTING.md
CONTRIBUTING

CODE_OF_CONDUCT - 
CODE_OF_CONDUCT.md


CHANGELOG -
CHANGELOG.md



RELEASE - 
RELEASE.md
